/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'

export class UserSchema extends BaseModel {
  static $columns = ['id', 'pass', 'role', 'user'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pass: string
  @column()
  declare role: string
  @column()
  declare user: string
}
