/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'

export class MedicineSchema extends BaseModel {
  static $columns = ['amount', 'dosage', 'id', 'manufacturer', 'name'] as const
  $columns = MedicineSchema.$columns
  @column()
  declare amount: number
  @column()
  declare dosage: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturer: string
  @column()
  declare name: string
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'pass', 'role', 'user'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pass: string
  @column()
  declare role: string
  @column()
  declare user: string
}
